version: "3"
services:
  dnd-postgres:
    container_name: postgres-dnd
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/clusters/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped
