version: "3"
services:
  dnd-postgres:
    container_name: dnd-postgres
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/clusters/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  dnd-bot:
    container_name: dnd-bot
    image: sushiwaumai/daily-news-discord
    env_file:
      - .env
    depends_on:
      - dnd-postgres
    restart: unless-stopped
