name: Deploy Application
on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Get files
        uses: actions/checkout@v2
      - name: Copy Data
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cp -r /root/app/dailynews/data /root/data/dailynews
      - name: Deploy with rsync
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: /
          remote_path: /root/app/dailynews
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Start Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo pnpm stop:prod
            cp -r /root/data/dailynews /root/app/dailynews
            cp /root/secrets/dailynews/env/.env.production /root/app/dailynews/.env.production
            cp /root/secrets/dailynews/env/.env.database /root/app/dailynews/packages/database/.env
            cd /root/app/dailynews/
            sudo pnpm deploy